{
 "title": "Helm Version Checker",
 "description": "Dashboard for viewing the status of production certificates. To be used with the helm-version-checker project.https://github.com/mogensen/helm-version-checker",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Outdated",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(helm_version_checker_is_latest == 0)"
    }
   ]
  },
  {
   "title": "Deprecated",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(helm_version_checker_is_deprecated == 1)"
    }
   ]
  },
  {
   "title": "Outdated Helm Releases",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(exported_namespace, name, installed_version, latest_version) (helm_version_checker_is_latest) == 0"
    }
   ]
  },
  {
   "title": "Deprecated Helm Releases",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(exported_namespace, name, installed_version, latest_version) (helm_version_checker_is_deprecated) == 1"
    }
   ]
  }
 ]
}